# Background and foreground colors
background = #000000
foreground = #97D863

# Standard colors
palette = 0=#000000
palette = 1=#9c86c2
palette = 2=#76cafe
palette = 3=#89ffff
palette = 4=#667ab9
palette = 5=#a19ef1
palette = 6=#8fdcff
palette = 7=#97D863

# Bright colors
palette = 8=#686163
palette = 9=#b498e3
palette = 10=#71e3ff
palette = 11=#66ffff
palette = 12=#758edc
palette = 13=#b6b0ff
palette = 14=#92f4ff
palette = 15=#f1f5ff
