$color = rgba(0, 0, 0, 1)
$inner_color = rgba(0, 0, 0, 0.66)
$outer_color = rgba(161, 158, 241, 1)
$font_color = rgba(151, 216, 99, 1)
$placeholder_color = rgba(151, 216, 99, 0.7)
$check_color = rgba(143, 220, 255, 1)
