background            #000000
foreground            #97D863

# black
color0  #000000
color8  #686163

# red
color1  #9c86c2
color9  #b498e3

# green
color2  #76cafe
color10 #71e3ff

# yellow
color3  #89ffff
color11 #66ffff

# blue
color4  #667ab9
color12 #758edc

# magenta
color5  #a19ef1
color13 #b6b0ff

#cyan
color6  #8fdcff
color14 #92f4ff

#white
color7  #97D863
color15 #f1f5ff


